apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: homeautomation
  namespace: argocd
  # Finalizer ensures that the project isn't deleted until apps are gone
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: "Core cluster homeautomation: Gateway API, DNS, Secrets, Certs etc."

  # Allow manifests to come from any repository you've connected
  sourceRepos:
  - "*"

  # Allow deployment to the local cluster and any namespace
  destinations:
  - namespace: "homeautomation"
    server: https://kubernetes.default.svc

  # Allow this project to create Cluster-level resources (like CRDs and Namespaces)
  clusterResourceWhitelist:
  - group: "*"
    kind: "*"