apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Pull and render the Headlamp chart from the Helm repository
helmCharts:
  - name: headlamp
    version: 0.39.0
    repo: https://kubernetes-sigs.github.io/headlamp/
    releaseName: headlamp
    namespace: kubernetes-dashboard

# Add HttpRoute
resources:
  - httproute.yml